name: Build NativeScript Application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install Python
        uses: actions/setup-python@v1

      - name: Install NativeScript
        run: |
          sudo gem install fastlane -NV
          python -m pip install --upgrade pip six
          npm i -g nativescript --ignore-scripts
          tns usage-reporting disable
          tns error-reporting disable
          tns doctor
          
      - name: Install Dependencies
        run: npm install
      
      - name: Build Android Application
        if: "false"
        run: tns build android --copy-to dist/build.apk
      
      - name: Build iOS Application
        run: |
          # tns build ios --copy-to dist/build.ipa
          fastlane ios build
        env:
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_ID }}"
          FASTLANE_APPLE_TEAM_ID: "${{ secrets.FASTLANE_APPLE_TEAM_ID }}"
          FASTLANE_IOS_APP_ID: "${{ secrets.FASTLANE_IOS_APP_ID }}"
          FASTLANE_MATCH_APP_ID: "${{ secrets.FASTLANE_MATCH_APP_ID }}"
          FASTLANE_MATCH_GIT_URL: "${{ secrets.FASTLANE_MATCH_GIT_URL }}"
          FASTLANE_MATCH_USERNAME: "${{ secrets.FASTLANE_MATCH_USERNAME }}"
          MATCH_PASSWORD: "${{ secrets.MATCH_PASSWORD }}"
          FASTLANE_PASSWORD: "${{ secrets.FASTLANE_PASSWORD }}"
          FASTLANE_SESSION: "${{ secrets.FASTLANE_SESSION }}"
          MATCH_PROVISIONING_PROFILE: "${{ secrets.MATCH_PROVISIONING_PROFILE }}"
          LANG: en_GB.UTF-8
          LC_ALL: en_GB.UTF-8
          
      - name: Upload Android Build
        if: "false"
        uses: actions/upload-artifact@v1
        with:
          name: Andorid Build
          path: ./dist/build.apk
                
      - name: Upload iOS Build
        uses: actions/upload-artifact@v1
        with:
          name: iOS Build
          path: ./dist/build.ipa
